module.exports = {
    "en": {
        "server_start": "Server started at ",
        "error_checking_trello_api": "Error checking Trello API: ",
        "checking_trello_api": "Checking Trello API...",
        "board_name": " | Board name: ",
        "hour": " | Hour: ",
        "new_changes": " | New changes: ",
        "new_action": "A new action has been found: ",
        "sending_to_discord": "Sending to Discord...",
        "error_sending_to_discord": "Error sending to Discord: ",
        "trello_create_card": "Create card:",
        "trello_create_card_desc": "A new card has been created.",
        "trello_desc": "Description",
        "trello_due_date": "Due date",
        "trello_dueComplete": "Completion status",
        "trello_idAttachmentCover": "Cover page",
        "trello_idChecklists": "Checklist",
        "trello_idMembers": "Members",
        "trello_idLabels": "Labels",
        "trello_idList": "List",
        "trello_update_card": "Update card:",
        "trello_update_card_desc": "A card has been updated.",
        "trello_previous_list": "Previous list",
        "trello_current_list": "Current list",
        "trello_previous_name": "Previous name",
        "trello_current_name": "Current name",
        "trello_previous_desc": "Previous description",
        "trello_current_desc": "Current description",
        "trello_previous_due": "Previous due date",
        "trello_current_due": "Current due date",
        "trello_previous_dueComplete": "Previous completion status",
        "trello_current_dueComplete": "Current completion status",
        "trello_previous_idAttachmentCover": "Previous cover",
        "trello_current_idAttachmentCover": "Current cover",
        "trello_previous_idChecklists": "Checklist added",
        "trello_delete_card": "Delete card",
        "trello_delete_card_desc": "A card has been deleted.",
        "trello_add_member_to_card": "Member added to card: ",
        "trello_add_member_to_card_desc": "A member has been added to a card.",
        "trello_remove_member_from_card": "Member removed from card: ",
        "trello_remove_member_from_card_desc": "A member has been removed from a card.",
        "trello_move_card_to_board": "Card moved to board: ",
        "trello_move_card_to_board_desc": "A card has been moved to another board.",
        "trello_update_list": "Card moved to list: ",
        "trello_update_list_desc": "A card has been moved to another list.",
        "trello_addChecklistToCard": "Checklist added to card: ",
        "trello_addChecklistToCard_desc": "A checklist has been added to a card.",
        "trello_removeChecklistFromCard": "Checklist removed from card: ",
        "trello_removeChecklistFromCard_desc": "A checklist has been removed from a card.",
        "trello_updateCheckItemStateOnCard": "Checklist updated: ",
        "trello_updateCheckItemStateOnCard_desc": "A checklist item state has been updated.",
        "trello_updateCheckItemStateOnCard_name": "Name",
        "trello_updateChecklist": "Update checklist: ",
        "trello_updateChecklist_desc": "A checklist has been updated.",
        "trello_updateChecklist_previous_name": "Previous name",
        "trello_updateChecklist_current_name": "Current name",
        "trello_action_not_supported": "Action not supported: ",
        "trello_action_not_supported_desc": "This action is not supported:"
    },    
    "es": {
        "server_start": "Servidor iniciado en ",
        "error_checking_trello_api": "Error al verificar la API de Trello: ",
        "checking_trello_api": "Verificando la API de Trello...",
        "board_name": " | Nombre del tablero: ",
        "hour": " | Hora: ",
        "new_changes": " | Nuevos cambios: ",
        "new_action": "Se ha encontrado una nueva acción: ",
        "sending_to_discord": "Enviando a Discord...",
        "error_sending_to_discord": "Error al enviar a Discord: ",
        "trello_create_card": "Crear tarjeta:",
        "trello_create_card_desc": "Se ha creado una nueva tarjeta.",
        "trello_desc": "Descripción",
        "trello_due_date": "Fecha de vencimiento",
        "trello_dueComplete": "Estado de finalización",
        "trello_idAttachmentCover": "Portada",
        "trello_idChecklists": "Checklist",
        "trello_idMembers": "Miembros",
        "trello_idLabels": "Etiquetas",
        "trello_idList": "Lista",
        "trello_update_card": "Actualizar tarjeta:",
        "trello_update_card_desc": "Una tarjeta ha sido actualizada.",
        "trello_previous_list": "Lista anterior",
        "trello_current_list": "Lista actual",
        "trello_previous_name": "Nombre anterior",
        "trello_current_name": "Nombre actual",
        "trello_previous_desc": "Descripción anterior",
        "trello_current_desc": "Descripción actual",
        "trello_previous_due": "Fecha de vencimiento anterior",
        "trello_current_due": "Fecha de vencimiento actual",
        "trello_previous_dueComplete": "Estado de finalización anterior",
        "trello_current_dueComplete": "Estado de finalización actual",
        "trello_previous_idAttachmentCover": "Portada anterior",
        "trello_current_idAttachmentCover": "Portada actual",
        "trello_previous_idChecklists": "Checklist añadido",
        "trello_delete_card": "Eliminar tarjeta",
        "trello_delete_card_desc": "Una tarjeta ha sido eliminada.",
        "trello_add_member_to_card": "Miembro añadido a la tarjeta: ",
        "trello_add_member_to_card_desc": "Un miembro ha sido añadido a una tarjeta.",
        "trello_remove_member_from_card": "Miembro eliminado de la tarjeta: ",
        "trello_remove_member_from_card_desc": "Un miembro ha sido eliminado de una tarjeta.",
        "trello_move_card_to_board": "Tarjeta movida al tablero: ",
        "trello_move_card_to_board_desc": "Una tarjeta ha sido movida a otro tablero.",
        "trello_update_list": "Tarjeta movida a la lista: ",
        "trello_update_list_desc": "Una tarjeta ha sido movida a otra lista.",
        "trello_addChecklistToCard": "Checklist añadido a la tarjeta: ",
        "trello_addChecklistToCard_desc": "Un checklist ha sido añadido a una tarjeta.",
        "trello_removeChecklistFromCard": "Checklist eliminado de la tarjeta: ",
        "trello_removeChecklistFromCard_desc": "Un checklist ha sido eliminado de una tarjeta.",
        "trello_updateCheckItemStateOnCard": "Checklist actualizado: ",
        "trello_updateCheckItemStateOnCard_desc": "El estado de un ítem en el checklist ha sido actualizado.",
        "trello_updateCheckItemStateOnCard_name": "Nombre",
        "trello_updateChecklist": "Actualizar checklist: ",
        "trello_updateChecklist_desc": "Un checklist ha sido actualizado.",
        "trello_updateChecklist_previous_name": "Nombre anterior",
        "trello_updateChecklist_current_name": "Nombre actual",
        "trello_action_not_supported": "Acción no soportada: ",
        "trello_action_not_supported_desc": "Esta acción no es soportada:"
    },    
    "de": {
        "server_start": "Server gestartet um ",
        "error_checking_trello_api": "Fehler beim Überprüfen der Trello-API: ",
        "checking_trello_api": "Überprüfung der Trello-API...",
        "board_name": " | Name des Boards: ",
        "hour": " | Uhrzeit: ",
        "new_changes": " | Neue Änderungen: ",
        "new_action": "Eine neue Aktion wurde gefunden: ",
        "sending_to_discord": "Senden an Discord...",
        "error_sending_to_discord": "Fehler beim Senden an Discord: ",
        "trello_create_card": "Karte erstellen:",
        "trello_create_card_desc": "Eine neue Karte wurde erstellt.",
        "trello_desc": "Beschreibung",
        "trello_due_date": "Fälligkeitsdatum",
        "trello_dueComplete": "Fertigstellungsstatus",
        "trello_idAttachmentCover": "Titelseite",
        "trello_idChecklists": "Checkliste",
        "trello_idMembers": "Mitglieder",
        "trello_idLabels": "Etiketten",
        "trello_idList": "Liste",
        "trello_update_card": "Karte aktualisieren:",
        "trello_update_card_desc": "Eine Karte wurde aktualisiert.",
        "trello_previous_list": "Vorherige Liste",
        "trello_current_list": "Aktuelle Liste",
        "trello_previous_name": "Vorheriger Name",
        "trello_current_name": "Aktueller Name",
        "trello_previous_desc": "Vorherige Beschreibung",
        "trello_current_desc": "Aktuelle Beschreibung",
        "trello_previous_due": "Vorheriges Fälligkeitsdatum",
        "trello_current_due": "Aktuelles Fälligkeitsdatum",
        "trello_previous_dueComplete": "Vorheriger Fertigstellungsstatus",
        "trello_current_dueComplete": "Aktueller Fertigstellungsstatus",
        "trello_previous_idAttachmentCover": "Vorherige Titelseite",
        "trello_current_idAttachmentCover": "Aktuelle Titelseite",
        "trello_previous_idChecklists": "Checkliste hinzugefügt",
        "trello_delete_card": "Karte löschen",
        "trello_delete_card_desc": "Eine Karte wurde gelöscht.",
        "trello_add_member_to_card": "Mitglied zur Karte hinzugefügt: ",
        "trello_add_member_to_card_desc": "Ein Mitglied wurde zu einer Karte hinzugefügt.",
        "trello_remove_member_from_card": "Mitglied von der Karte entfernt: ",
        "trello_remove_member_from_card_desc": "Ein Mitglied wurde von einer Karte entfernt.",
        "trello_move_card_to_board": "Karte zu Board verschoben: ",
        "trello_move_card_to_board_desc": "Eine Karte wurde auf ein anderes Board verschoben.",
        "trello_update_list": "Karte zu Liste verschoben: ",
        "trello_update_list_desc": "Eine Karte wurde auf eine andere Liste verschoben.",
        "trello_addChecklistToCard": "Checkliste zur Karte hinzugefügt: ",
        "trello_addChecklistToCard_desc": "Eine Checkliste wurde zu einer Karte hinzugefügt.",
        "trello_removeChecklistFromCard": "Checkliste von der Karte entfernt: ",
        "trello_removeChecklistFromCard_desc": "Eine Checkliste wurde von einer Karte entfernt.",
        "trello_updateCheckItemStateOnCard": "Checkliste aktualisiert: ",
        "trello_updateCheckItemStateOnCard_desc": "Der Status eines Checklisten-Items wurde aktualisiert.",
        "trello_updateCheckItemStateOnCard_name": "Name",
        "trello_updateChecklist": "Checkliste aktualisieren: ",
        "trello_updateChecklist_desc": "Eine Checkliste wurde aktualisiert.",
        "trello_updateChecklist_previous_name": "Vorheriger Name",
        "trello_updateChecklist_current_name": "Aktueller Name",
        "trello_action_not_supported": "Aktion nicht unterstützt: ",
        "trello_action_not_supported_desc": "Diese Aktion wird nicht unterstützt:"
    }    
};